const D=window.KOMPAS_DATA,$=id=>document.getElementById(id);let current=null;
const locOpts=()=>D.locations.map(x=>`<option>${x}</option>`).join("");
function show(id){["start","form","log"].forEach(x=>$(x).classList.toggle("hidden",x!==id));if(id==="start")renderList()}
function resetAll(){current=null;$("search").value="";$("extra").value="";show("start")}
function renderList(){let q=$("search").value.toLowerCase(),h="";[...new Set(D.observations.map(x=>x.category))].forEach(c=>{let a=D.observations.filter(x=>x.category===c&&x.name.toLowerCase().includes(q)&&(x.id!=="installatie_videofoon"||v("projectType")==="Appartement"));if(!a.length)return;h+=`<div class="group">${c}</div>`;a.forEach(x=>h+=`<button data-id="${x.id}">${x.name}<span class="small">${x.cardType==="expert"?"Expertkaart":"Registratiekaart"}</span></button>`)});$("list").innerHTML=h;document.querySelectorAll("[data-id]").forEach(b=>b.onclick=()=>openCard(b.dataset.id))}
function fillRegistration(){let objects=current?.id==="manco"?D.objects.filter(x=>x.id!=="installatie"):D.objects;$("object").innerHTML=objects.map(x=>`<option value="${x.id}">${x.name}</option>`).join("");objectChanged();}
function objectChanged(){let o=D.objects.find(x=>x.id===$("object").value);$("type").innerHTML=o.types.map(x=>`<option>${x}</option>`).join("");typeChanged()}
function typeChanged(){let o=D.objects.find(x=>x.id===$("object").value),p=o.partsByType?o.partsByType[$("type").value]:o.parts;$("part").innerHTML=p.map(x=>`<option>${x}</option>`).join("");$("location").innerHTML=locOpts();render()}
function openCard(id){current=D.observations.find(x=>x.id===id);$("cardTitle").textContent=current.name;$("cardType").textContent=current.cardType==="expert"?"Expertkaart":"Registratiekaart";$("registrationFields").classList.toggle("hidden",current.cardType==="expert");$("microLocationWrap").classList.toggle("hidden",id!=="lakbeschadiging");$("microLocation").value="Niet gespecificeerd";$("expert").innerHTML="";if(current.cardType==="registration")fillRegistration();else buildExpert(id);show("form");render()}
const field=(id,label,html)=>`<label>${label}${html.startsWith("<select")?html.replace("<select",`<select id="${id}"`):html.replace("<input",`<input id="${id}"`)}</label>`;
const select=(opts)=>`<select>${opts.map(x=>`<option>${x}</option>`).join("")}</select>`;
const input=(type,value,step="1")=>`<input type="${type}" value="${value}" step="${step}">`;
function shell(code,title,fields){$("expert").innerHTML=`<div class="expert-card"><h3>${code} ${title}</h3><div class="expert-fields">${fields}</div><div id="assessment" class="note"></div>${["Vaktechnische onderbouwing","Bron","Waarom deze inschatting?","Praktijkadvies","Tips voor de inspecteur"].map((x,i)=>`<details><summary>${x}</summary><div id="know${i}"></div></details>`).join("")}</div>`;$("expert").querySelectorAll("select,input").forEach(e=>{e.onchange=render;e.oninput=render})}
function buildExpert(id){
if(id==="beglazing_beschadigd")shell("E-001","Beschadiging isolatieglas",field("eLoc","Locatie",select(D.locations))+field("side","Zijde",select(["Binnenzijde","Buitenzijde","Spouw"]))+field("zone","Zone",select(["M","E","R"]))+field("length","Lengte langste beschadiging (mm)",input("number","16"))+field("glassCount","Aantal lijnvormige beschadigingen",input("number","1"))+field("glassTotal","Totale lengte beschadigingen (mm)",input("number","16"))+field("distance","Zichtbaar vanaf minimaal 3 meter?",select(["Ja","Nee"]))+field("weather","Omstandigheden",select(["Diffuus daglicht / bewolkt","Direct zonlicht","Kunstlicht"])));
if(id==="hol_klinkende_tegel")shell("E-002","Hol klinkende tegel",field("kind","Tegelwerk",select(["Vloertegelwerk","Wandtegelwerk"]))+field("eLoc","Locatie",select(D.locations))+field("count","Aantal tegels",input("number","1"))+field("connected","Aaneengesloten?",select(["Nee","Ja"]))+field("movement","Beweging?",select(["Nee","Ja"]))+field("loose","Aantoonbaar los?",select(["Nee","Ja"]))+field("crack","Scheurvorming?",select(["Nee","Ja"]))+field("joint","Voegschade?",select(["Nee","Ja"]))+field("level","Hoogteverschil?",select(["Nee","Ja"])));
if(id==="hoogteverschil_tegelwerk")shell("E-003","Hoogteverschil tegelwerk",field("kind","Tegelwerk",select(["Vloertegelwerk","Wandtegelwerk"]))+field("eLoc","Locatie",select(D.locations))+field("value","Hoogteverschil (mm)",input("number","1.2","0.1"))+field("jointWidth","Voegbreedte (mm)",input("number","2","0.5"))+field("method","Meetmethode",select(["Meetwig","Voelermaat","Digitale schuifmaat","Anders"]))+field("sharp","Scherpe rand?",select(["Nee","Ja"]))+field("trip","Struikelgevaar?",select(["Nee","Ja"])));
if(id==="behangklare_wand")shell("E-004","Behangklare wand",field("eLoc","Locatie",select(D.locations))+field("issue","Waarneming",select(["Gat","Beschadiging","Kras","Oneffenheid","Open naad","Scheur","Krimpscheur","Plamuur zichtbaar","Schroefkop zichtbaar","Onvoldoende afgewerkt","Vervuiling","Overig"]))+field("size","Omvang",select(["Kleiner dan een 20 eurocentmunt","Groter dan een 20 eurocentmunt"]))+field("finish","Beoogde eindafwerking",select(["Onbekend","Behang","Renovlies","Schilderwerk","Stucwerk"])));
if(id==="spackwerk")shell("E-005","Spack-/spuitwerk",field("surface","Ondergrond",select(["Plafond","Wand"]))+field("eLoc","Locatie",select(D.locations))+field("issue","Waarneming",select(["Beschadiging","Smet","Vervuiling","Schrale dekking","Structuurverschil","Reparatie zichtbaar","Verkleuring","Los materiaal","Onvoldoende dekking"]))+field("extent","Omvang",select(["Plaatselijk","Meerdere plaatsen","Groot oppervlak"])));
if(id==="lakwerk")shell("E-006","Lakwerk",field("objectPaint","Object",select(["Deur","Kozijn","Trap","Leuning","Overig gelakt bouwdeel"]))+field("eLoc","Locatie",select(D.locations))+field("issue","Waarneming",select(["Kras","Beschadiging","Druiper","Zakker","Schrale dekking","Stofinsluiting","Kleurverschil","Glansverschil","Reparatie zichtbaar","Structuurverschil"]))+field("distancePaint","Zichtbaar vanaf normale kijkafstand?",select(["Ja","Nee"]))+field("lightPaint","Omstandigheden",select(["Normaal daglicht","Strijklicht","Kunstlicht"])));
if(id==="kitwerk")shell("E-007","Kitwerk",field("kitPlace","Locatie / toepassing",select(["Badkamer","Toilet","Keuken","Kozijn binnen","Kozijn buiten","Gevel","Balkon","Galerij","Overig"]))+field("issue","Waarneming",select(["Kit ontbreekt","Onderbreking","Onthechting","Gescheurd","Poreus","Onvoldoende gevuld","Slordig afgewerkt","Vervuild","Verkeerde kleur","Loslatend","Verkeerd materiaal – aantoonbaar"]))+field("waterLoad","Waterbelast?",select(["Nee","Ja"])));
if(id==="installatie_ventilatie")shell("I-001","Ventilatie",field("eLoc","Locatie",select(D.locations))+field("instPart","Onderdeel",select(["Ventiel","Bediening","Kanaalaansluiting"]))+field("instIssue","Waarneming",select(["Ontbreekt","Sluit niet aan","Beschadigd","Vervuild","Scheef aangebracht","Niet afgemonteerd","Werkt niet"]))+field("instSurface","Aansluiting op",select(["Plafond","Wand","Niet van toepassing"])));
if(id==="installatie_wtw"){shell("I-002","WTW-unit",field("eLoc","Locatie",select(["Technische ruimte"]))+field("instPart","Onderdeel",select(["WTW-unit","Display","Filter","Filterdeksel","Condensaansluiting","Kanaalaansluiting","Ventilator","Behuizing","Ophanging"]))+field("instIssue","Waarneming",select(["Beschadigd"])));updateInstallationIssues();$("instPart").onchange=()=>{updateInstallationIssues();render()}}
if(id==="installatie_warmtepomp"){shell("I-003","Warmtepomp",field("eLoc","Locatie",select(["Technische ruimte","Berging"]))+field("instPart","Onderdeel",select(["Binnenunit","Buitenunit","Display","Displaybeglazing","Manometer broncircuit","Manometer verwarmingsinstallatie","Leidingwerk","Leidingisolatie","Condensafvoer","Aansluiting","Bevestiging"]))+field("instIssue","Waarneming",select(["Beschadigd"])));updateInstallationIssues();$("instPart").onchange=()=>{updateInstallationIssues();render()}}
if(id==="installatie_omvormer")shell("I-004","Omvormer zonnepanelen",field("instPart","Onderdeel",select(["Omvormer","Behuizing","Display","Bekabeling","Aansluiting","Montagebeugel","Label"]))+field("instIssue","Waarneming",select(["Ontbreekt","Niet compleet","Beschadigd","Niet aangesloten","Werkt niet","Storing zichtbaar","Los aangebracht","Bekabeling niet deugdelijk afgewerkt","Label ontbreekt"])));
if(id==="installatie_rookmelder")shell("I-005","Rookmelder",field("eLoc","Locatie",select(["Vluchtroute"]))+field("instPart","Onderdeel",select(["Rookmelder","Montagevoet","Stofkap"]))+field("instIssue","Waarneming",select(["Ontbreekt","Niet afgemonteerd","Beschadigd","Scheef aangebracht","Niet aangesloten","Stofkap ontbreekt","Werkt niet"])));
if(id==="installatie_elektra"){shell("I-006","Elektra / groepenkast",field("instSystem","Installatie",select(["Wandcontactdoos","Schakelaar","Groepenkast"]))+field("eLoc","Locatie",select(D.locations))+field("instPart","Onderdeel",select(["Wandcontactdoos"]))+field("instIssue","Waarneming",select(["Ontbreekt","Niet compleet","Beschadigd","Niet aangesloten","Scheef aangebracht","Werkt niet","Los aangebracht","Label ontbreekt"])));updateElectricalFields();$("instSystem").onchange=()=>{updateElectricalFields();render()};$("instPart").onchange=()=>{updateElectricalIssues();render()}}
if(id==="installatie_vloerverdeler"){shell("I-007","Vloerverdeler",field("eLoc","Locatie",select(["Technische ruimte","Berging"]))+field("instPart","Onderdeel",select(["Verdeler","Pomp","Manometer","Leidingen","Afsluiters","Isolatie"]))+field("instIssue","Waarneming",select(["Beschadigd"])));updateInstallationIssues();$("instPart").onchange=()=>{updateInstallationIssues();render()}}
if(id==="installatie_wasmachine"){shell("I-008","Wasmachine-/drogeropstelling",field("eLoc","Locatie",select(["Technische ruimte","Berging","Badkamer"]))+field("instPart","Onderdeel",select(["Wasmachinekraan","Afvoer","Sifon","Wandcontactdoos wasmachine","Wandcontactdoos droger","Dubbele wandcontactdoos","Aansluiting"]))+field("instIssue","Waarneming",select(["Ontbreekt","Niet compleet","Beschadigd","Niet aangesloten","Lekt","Los aangebracht","Werkt niet","Afvoer onvoldoende"])));}

if(id==="sanitair_toilet")shell("S-001","Toilet",
field("sanRoom","Ruimte",select(["Toilet","Badkamer"]))+
field("sanPart","Onderdeel",select(["Toiletpot","Toiletbril","Reservoir","Spoelplaat","Bevestiging","Aansluiting","Kitwerk"]))+
field("sanIssue","Waarneming",select(["Beschadigd","Los","Scheef gemonteerd","Niet compleet","Ontbreekt","Werkt niet","Lekt","Spoelt niet goed","Kit ontbreekt","Kit onthecht","Onvoldoende afgewerkt"]))+
field("toiletHeight","Hoogte toiletpot zonder toiletbril (cm)",input("number","42","0.5"))+
field("toiletMorework","Hoogte conform meerwerk",select(["Niet van toepassing","Hoger geplaatst conform meerwerk","Lager geplaatst conform meerwerk","Afwijkende hoogte conform meerwerk"]))+
field("checkFlush","Spoeling gecontroleerd?",select(["Ja","Nee"]))+
field("checkStable","Toiletpot stabiel?",select(["Ja","Nee"])));

if(id==="sanitair_wastafel"){shell("S-002","Wastafel / fontein",
field("sanRoom","Ruimte",select(["Badkamer","Toilet"]))+
field("sanPart","Onderdeel",select(["Wastafel","Fontein","Badmeubel","Lade links","Lade rechts","Front","Greep","Spiegel","Spiegelkast","Kraan","Afvoer","Overloop","Aansluiting","Kitwerk"]))+
field("sanIssue","Waarneming",select(["Beschadigd"]))+
field("checkWater","Waterloop gecontroleerd?",select(["Ja","Nee"]))+
field("checkDrain","Afvoer gecontroleerd?",select(["Ja","Nee"])));updateSanitaryIssues();$("sanPart").onchange=()=>{updateSanitaryIssues();render()}}

if(id==="sanitair_douche")shell("S-003","Douche",
field("sanRoom","Ruimte",select(["Badkamer"]))+
field("sanPart","Onderdeel",select(["Douchegoot","Drain","Douchewand","Beglazing","Beslag","Douchekraan","Afvoer","Kitwerk","Tegelwerk"]))+
field("sanIssue","Waarneming",select(["Beschadigd","Kras","Los","Scheef gemonteerd","Niet compleet","Ontbreekt","Werkt niet","Lekt","Afvoer onvoldoende","Kit ontbreekt","Kit onderbroken","Afschot onvoldoende","Onvoldoende afgewerkt"]))+
field("checkWater","Waterloop gecontroleerd?",select(["Ja","Nee"]))+
field("checkDrain","Afvoer gecontroleerd?",select(["Ja","Nee"])));

if(id==="sanitair_bad")shell("S-004","Bad",
field("sanRoom","Ruimte",select(["Badkamer"]))+
field("sanPart","Onderdeel",select(["Bad","Badpaneel","Badkraan","Overloop","Afvoer","Aansluiting","Kitwerk"]))+
field("sanIssue","Waarneming",select(["Beschadigd","Kras","Los","Scheef gemonteerd","Niet compleet","Ontbreekt","Werkt niet","Lekt","Afvoer onvoldoende","Kit ontbreekt","Kit onthecht","Onvoldoende afgewerkt"]))+
field("checkWater","Waterloop gecontroleerd?",select(["Ja","Nee"]))+
field("checkDrain","Afvoer gecontroleerd?",select(["Ja","Nee"])));

if(id==="sanitair_kraan")shell("S-005","Kraan",
field("sanRoom","Ruimte",select(["Badkamer","Toilet","Keuken"]))+
field("sanPart","Onderdeel",select(["Wastafelkraan","Fonteinkraan","Douchekraan","Badkraan","Keukenkraan"]))+
field("sanIssue","Waarneming",select(["Beschadigd","Kras","Los","Scheef gemonteerd","Niet compleet","Ontbreekt","Werkt niet","Druppelt","Lekt","Bediening zwaar","Onvoldoende afgewerkt"]))+
field("checkWater","Werking gecontroleerd?",select(["Ja","Nee"])));

if(id==="installatie_designradiator"){shell("I-009","Designradiator",
field("eLoc","Locatie",select(["Badkamer"]))+
field("instPart","Onderdeel",select(["Radiator","Bevestiging","Bediening","Afstandsbediening"]))+
field("instIssue","Waarneming",select(["Beschadigd"])));updateDesignRadiatorIssues();$("instPart").onchange=()=>{updateDesignRadiatorIssues();render()}}
if(id==="installatie_videofoon"){shell("I-010","Videofoon",field("eLoc","Locatie",select(["Hal","Woonkamer"]))+field("instPart","Onderdeel",select(["Binnenpost","Display","Hoorn","Bediening","Bevestiging"]))+field("instIssue","Waarneming",select(["Ontbreekt","Beschadigd","Los aangebracht","Scheef aangebracht","Werkt niet","Beeld ontbreekt","Geluid ontbreekt","Deuropener werkt niet"])));}
if(id==="installatie_loze_leiding"){shell("I-011","Loze leiding",field("eLoc","Locatie",select(D.locations))+field("instPart","Onderdeel",select(["Loze leiding","Inbouwdoos","Afdekplaat","Uitmonding"]))+field("instIssue","Waarneming",select(["Ontbreekt","Niet compleet","Beschadigd","Niet bereikbaar","Niet doorvoerbaar","Afdekplaat ontbreekt"]))+field("controlWire","Controledraad aanwezig?",select(["Ja","Nee","Niet gecontroleerd"])));}

}
function setOptions(el,items){el.innerHTML=items.map(x=>`<option>${x}</option>`).join("")}
function updateElectricalIssues(){if(!$("instPart")||!$("instIssue"))return;let p=v("instPart"),issues=["Ontbreekt","Niet compleet","Beschadigd","Niet aangesloten","Scheef aangebracht","Werkt niet","Los aangebracht"];if(p==="Groepenverklaring")issues=["Ontbreekt","Onvolledig","Niet leesbaar","Komt niet overeen met de groepenkast"];if(p==="Label")issues=["Ontbreekt","Onvolledig","Niet leesbaar"];setOptions($("instIssue"),issues)}
function updateElectricalFields(){if(!$("instSystem"))return;let system=v("instSystem"),loc=$("eLoc"),part=$("instPart");if(system==="Groepenkast"){setOptions(loc,["Meterkast"]);setOptions(part,["Groepenkast","Afdekplaat","Blindplaat","Automaat","Aardlekschakelaar","Hoofdschakelaar","Label","Groepenverklaring","Aansluiting"])}else{setOptions(loc,D.locations);setOptions(part,system==="Schakelaar"?["Schakelaar","Afdekraam","Aansluiting"]:["Wandcontactdoos","Afdekraam","Aansluiting"])}updateElectricalIssues()}
function updateInstallationIssues(){if(!$("instPart")||!$("instIssue"))return;let id=current?.id,p=v("instPart"),issues=["Ontbreekt","Niet compleet","Beschadigd","Niet aangesloten","Sluit niet aan","Werkt niet","Storing zichtbaar","Los aangebracht"];
if(id==="installatie_wtw"){if(p==="WTW-unit")issues=["Beschadigd","Trillingen","Afwijkend geluid","Werkt niet","Storing zichtbaar","Los aangebracht"];else if(p==="Filter")issues=["Ontbreekt","Vervuild","Beschadigd"];else if(p==="Display")issues=["Beschadigd","Werkt niet","Storing zichtbaar"];else if(p==="Condensaansluiting")issues=["Ontbreekt","Niet aangesloten","Lekt","Sluit niet aan"];else if(p==="Ventilator")issues=["Afwijkend geluid","Werkt niet","Beschadigd"];else issues=["Ontbreekt","Niet compleet","Beschadigd","Niet aangesloten","Sluit niet aan","Los aangebracht"]}
if(id==="installatie_warmtepomp"){if(p==="Manometer broncircuit"||p==="Manometer verwarmingsinstallatie")issues=["Druk lager dan 1 bar","Druk hoger dan 2 bar","Beschadigd","Niet leesbaar"];else if(p==="Displaybeglazing")issues=["Gebarsten","Beschadigd"];else if(p==="Leidingisolatie")issues=["Ontbreekt","Onderbroken","Beschadigd"];else if(p==="Condensafvoer")issues=["Lekt","Niet aangesloten","Sluit niet aan","Verstopt"];else issues=["Ontbreekt","Niet compleet","Beschadigd","Niet aangesloten","Sluit niet aan","Werkt niet","Storing zichtbaar","Los aangebracht","Lekkage zichtbaar"]}
if(id==="installatie_vloerverdeler"){if(p==="Manometer")issues=["Druk lager dan 1 bar","Druk hoger dan 2 bar","Beschadigd","Niet leesbaar"];else if(p==="Leidingen")issues=["Lekt","Zweet","Beschadigd","Niet aangesloten","Isolatie ontbreekt"];else issues=["Ontbreekt","Niet compleet","Beschadigd","Niet aangesloten","Werkt niet","Lekt","Los aangebracht"]}
setOptions($("instIssue"),issues)}
function updateSanitaryIssues(){if(current?.id!=="sanitair_wastafel"||!$("sanPart")||!$("sanIssue"))return;let p=v("sanPart"),issues;
if(["Lade links","Lade rechts"].includes(p))issues=["Beschadigd","Loopt zwaar","Sluit niet","Scheef gemonteerd","Los gemonteerd"];
else if(p==="Badmeubel")issues=["Beschadigd","Kras","Los","Scheef gemonteerd","Niet compleet","Onvoldoende afgewerkt"];
else if(p==="Front")issues=["Beschadigd","Kras","Scheef gemonteerd","Los gemonteerd"];
else if(p==="Greep")issues=["Beschadigd","Los","Ontbreekt"];
else if(["Spiegel","Spiegelkast"].includes(p))issues=["Beschadigd","Kras","Los","Scheef gemonteerd","Niet compleet"];
else if(["Afvoer","Overloop","Aansluiting"].includes(p))issues=["Ontbreekt","Niet compleet","Lekt","Afvoer verstopt","Onvoldoende afgewerkt"];
else if(p==="Kitwerk")issues=["Kit ontbreekt","Kit onthecht","Onvoldoende afgewerkt"];
else issues=["Beschadigd","Kras","Los","Scheef gemonteerd","Niet compleet","Ontbreekt","Werkt niet","Lekt","Onvoldoende afgewerkt"];
setOptions($("sanIssue"),issues)}

function updateDesignRadiatorIssues(){if(current?.id!=="installatie_designradiator"||!$("instPart")||!$("instIssue"))return;let p=v("instPart"),issues;
if(p==="Radiator")issues=["Beschadigd","Los aangebracht","Scheef aangebracht","Werkt niet","Lekt"];
else if(p==="Bevestiging")issues=["Los aangebracht","Beschadigd"];
else if(p==="Bediening")issues=["Werkt niet","Beschadigd"];
else if(p==="Afstandsbediening")issues=["Ontbreekt","Beschadigd","Werkt niet"];
setOptions($("instIssue"),issues)}
function v(id){return $(id)?.value||""} function n(id){return Number(v(id)||0)} function one(n,one,many){return n===1?one:many}
function expertResult(){
let id=current.id,q="Opleverpunt",title="",desc="",k=[];
if(id==="beglazing_beschadigd"){let zone=v("zone"),lim=zone==="E"?30:15,countLimit=zone==="E"?4:2,totalLimit=zone==="E"?90:45,longest=n("length"),count=Math.max(1,n("glassCount")),total=n("glassTotal"),overLongest=longest>lim,overCount=count>countLimit,overTotal=total>totalLimit,over=overLongest||overCount||overTotal; if(zone==="R"||v("distance")==="Nee"||v("weather")!=="Diffuus daglicht / bewolkt"||!over)q="Constatering";let pos=v("side")==="Spouw"?"in de spouw":`aan de ${v("side").toLowerCase()}`;title=`${q} - Beglazing beschadigd - ${v("eLoc")}`;desc=`Beschadiging waargenomen aan het isolatieglas in ${v("eLoc").toLowerCase()}. De beschadiging bevindt zich ${pos}, in zone ${zone}, is ${v("distance")==="Ja"?"zichtbaar":"niet zichtbaar"} vanaf minimaal 3 meter en is geconstateerd bij ${v("weather").toLowerCase()}. Er ${count===1?"is":"zijn"} ${count} lijnvormige ${count===1?"beschadiging":"beschadigingen"} waargenomen. De langste beschadiging bedraagt ${longest} mm en de totale lengte bedraagt ${total} mm.${zone!=="R"?` Voor zone ${zone} geldt maximaal ${countLimit} ${countLimit===1?"beschadiging":"beschadigingen"}, een maximale individuele lengte van ${lim} mm en een maximale totale lengte van ${totalLimit} mm.`:""}`;let exceeded=[];if(overLongest)exceeded.push(`de individuele lengte van ${lim} mm`);if(overCount)exceeded.push(`het toegestane aantal van ${countLimit}`);if(overTotal)exceeded.push(`de totale lengte van ${totalLimit} mm`);k=["De beoordeling vindt plaats op doorzicht, vanaf minimaal 3 meter en bij diffuus daglicht. Naast de individuele lengte worden ook het aantal en de gezamenlijke lengte van lijnvormige beschadigingen beoordeeld.","Kenniscentrum Glas, Beoordeling van meerbladig isolatieglas bij oplevering; samenvatting NEN-EN 1279:2018.",q==="Opleverpunt"?`De beschadigingen zijn onder passende omstandigheden zichtbaar en overschrijden ${exceeded.join(" en ")}.`:"De beoordelingsomstandigheden en gemeten waarden leiden niet tot een directe kwalificatie als opleverpunt.","Leg zijde, zone, langste lengte, aantal, totale lengte, kijkafstand en lichtomstandigheden vast.","Beoordeel vóór markering, bij diffuus daglicht en zo loodrecht mogelijk."];}
if(id==="hol_klinkende_tegel"){let c=Math.max(1,n("count"));q=["Ja"].some(x=>v("movement")===x||v("loose")===x||v("crack")===x||v("joint")===x||v("level")===x)?"Opleverpunt":"Constatering";title=`${q} - Hol klinkende tegel - ${v("kind")} - ${v("eLoc")}`;desc=`Bij lichte beklopping ${one(c,"klinkt","klinken")} ${c} ${one(c,"tegel","tegels")} van het ${v("kind").toLowerCase()} in ${v("eLoc").toLowerCase()} afwijkend en hol ten opzichte van de omliggende tegels. ${one(c,"De tegel ligt","De tegels liggen")} ${v("connected")==="Ja"?"aaneengesloten":"niet aaneengesloten"}. ${v("movement")==="Ja"?"Beweging is waarneembaar.":"Er is geen beweging waarneembaar."}`;k=["Een afwijkend geluid alleen bewijst niet dat het tegelwerk niet voldoet. Bekloppen toont het werkelijke lijmcontactoppervlak niet aan.","SKG-IKOB Uitvoeringsrichtlijn 35-101, paragraaf 6.5 en hoofdstuk 7.",q==="Opleverpunt"?"Naast het geluid is minimaal één bijkomend verschijnsel vastgesteld.":"Er zijn geen bijkomende verschijnselen vastgesteld.","Leg meerdere aaneengesloten tegels altijd vast.","Vergelijk omliggende tegels en controleer beweging, scheuren en voegschade."];}
if(id==="hoogteverschil_tegelwerk"){q=n("value")>1||v("trip")==="Ja"?"Opleverpunt":"Constatering";title=`${q} - Hoogteverschil tegelwerk - ${v("kind")} - ${v("eLoc")}`;desc=`Ter plaatse van het ${v("kind").toLowerCase()} in ${v("eLoc").toLowerCase()} is een hoogteverschil van ${n("value").toFixed(1).replace(".",",")} mm tussen twee aangrenzende tegelranden gemeten. De voegbreedte bedraagt ${n("jointWidth").toFixed(1).replace(".",",")} mm. De meting is uitgevoerd met ${v("method").toLowerCase()}.`;k=["De referentielimiet voor het hoogteverschil tussen aangrenzende tegelranden is 1,0 mm.","SKG-IKOB Uitvoeringsrichtlijn 35-101, paragraaf 7.3; ISO 7976-1 en ISO 7976-2.",q==="Opleverpunt"?"De gemeten waarde overschrijdt 1,0 mm of er is struikelgevaar.":"De gemeten waarde blijft binnen 1,0 mm.","Noteer meetwaarde en meetmethode.","Beoordeel hol klinken afzonderlijk; dat hoort niet in deze kaart."];}
if(id==="behangklare_wand"){let issue=v("issue");q=["Gat","Beschadiging","Open naad","Scheur","Schroefkop zichtbaar","Onvoldoende afgewerkt"].includes(issue)?"Opleverpunt":"Constatering";if(issue==="Gat"&&v("size")==="Kleiner dan een 20 eurocentmunt")q="Constatering";if(issue==="Krimpscheur")q="Constatering";title=`${q} - ${issue} - Wand - ${v("eLoc")}`;desc=`${issue} waargenomen aan de behangklare wand in ${v("eLoc").toLowerCase()}.`;if(issue==="Gat")desc+=` De omvang is ${v("size").toLowerCase()}.`;if(issue==="Krimpscheur")desc+=" Beoordeel afzonderlijk of de aansluitende afwerking, waaronder spackwerk, door de scheur is beschadigd.";k=["Behangklaar is een ondergrond voor verdere afwerking en is niet gelijk aan sausklaar. Kleine gaatjes tot circa de grootte van een 20 eurocentmunt kunnen binnen de gebruikelijke uitvoeringskwaliteit vallen. Deze maatvoering geldt uitsluitend voor gaatjes en niet voor scheuren.","Projectspecifieke technische omschrijving en STABU-afwerkingsomschrijving; bij ontbreken daarvan de gebruikelijke uitvoeringspraktijk.",issue==="Krimpscheur"?"Een krimpscheur kan op zichzelf als constatering worden vastgelegd. Wanneer aangrenzend spackwerk door onvoldoende insnijding is beschadigd, moet die gevolgschade afzonderlijk als opleverpunt worden beoordeeld.":q==="Opleverpunt"?"De afwijking kan de normale verdere wandafwerking belemmeren.":"De afwijking kan passen binnen de gebruikelijke kwaliteit van behangklaar werk.","Beoordeel volgens de overeengekomen afwerking, niet volgens de later gekozen eindafwerking.","Controleer de technische omschrijving. Strijklicht mag niet worden gebruikt bij de beoordeling van behangklaar werk."];}
if(id==="spackwerk"){q="Opleverpunt";title=`${q} - ${v("issue")} spackwerk - ${v("surface")} - ${v("eLoc")}`;desc=`${v("issue")} waargenomen aan het spack-/spuitwerk van ${v("surface")==="Plafond"?"het plafond":"de wand"} in ${v("eLoc").toLowerCase()}. De afwijking is ${v("extent").toLowerCase()} aanwezig.`;k=["Het gerede spack-/spuitwerk dient een samenhangende en voldoende gelijkmatige afwerking te vormen, passend bij de overeengekomen kwaliteit.","Projectspecifieke technische omschrijving, verwerkingsvoorschriften en gebruikelijke uitvoeringspraktijk.",`De waarneming ‘${v("issue").toLowerCase()}’ betreft een zichtbare afwijking van het gerede oppervlak.`,"Beschrijf alleen het zichtbare resultaat; schrijf geen herstelwijze voor.","Beoordeel bij normale lichtomstandigheden en noteer de omvang."];}
if(id==="lakwerk"){q=v("distancePaint")==="Ja"&&v("lightPaint")==="Normaal daglicht"?"Opleverpunt":"Constatering";title=`${q} - ${v("issue")} lakwerk - ${v("objectPaint")} - ${v("eLoc")}`;desc=`${v("issue")} waargenomen aan het lakwerk van de ${v("objectPaint").toLowerCase()} in ${v("eLoc").toLowerCase()}. De afwijking is ${v("distancePaint")==="Ja"?"zichtbaar":"niet zichtbaar"} vanaf normale kijkafstand en is beoordeeld bij ${v("lightPaint").toLowerCase()}.`;k=["Lakwerk wordt visueel beoordeeld onder normale gebruiks- en lichtomstandigheden. Strijklicht kan kleine onregelmatigheden onevenredig benadrukken.","Projectspecifieke afwerkingseisen, verwerkingsvoorschriften en gebruikelijke uitvoeringspraktijk.",q==="Opleverpunt"?"De afwijking is bij normale omstandigheden vanaf normale kijkafstand zichtbaar.":"De afwijking is alleen onder afwijkende omstandigheden of van zeer nabij zichtbaar.","Leg object, locatie, waarneming en beoordelingsomstandigheden vast.","Gebruik lakbeschadiging alleen voor het gelakte oppervlak, niet voor beslag of scharnieren."];}
if(id==="kitwerk"){q="Opleverpunt";title=`${q} - ${v("issue")} - Kitwerk - ${v("kitPlace")}`;desc=`${v("issue")} waargenomen aan het kitwerk in ${v("kitPlace").toLowerCase()}. De aansluiting is ${v("waterLoad")==="Ja"?"waterbelast":"niet waterbelast"}.`;k=["Kitvoegen moeten passend zijn voor de toepassing, voldoende gevuld en gehecht zijn en een doorlopende aansluiting vormen. In waterbelaste situaties is de continuïteit extra relevant.","NEN-EN 15651-1, BRL 2803, projectspecificatie en verwerkingsvoorschriften van de kitproducent.",`De waarneming ‘${v("issue").toLowerCase()}’ kan de afdichting, duurzaamheid of visuele kwaliteit beïnvloeden.`,"Noteer de zichtbare afwijking en toepassing; bepaal niet zonder bewijs welk product is gebruikt.","Controleer vooral hoeken, materiaalovergangen en aansluitingen bij sanitair, kozijnen en goten."];}
if(id.startsWith("installatie_")){q="Opleverpunt";let kaart=current.name,loc=v("eLoc"),onderdeel=v("instPart"),waarneming=v("instIssue"),systeem=id==="installatie_elektra"?v("instSystem"):kaart;
if(id==="installatie_omvormer"){title=`${q} - ${onderdeel} ${waarneming.toLowerCase()} - Omvormer zonnepanelen`;loc=""}
else if(id==="installatie_rookmelder"){title=`${q} - ${onderdeel} ${waarneming.toLowerCase()} - Vluchtroute`}
else if(id==="installatie_elektra"){title=`${q} - ${onderdeel} ${waarneming.toLowerCase()} - ${loc}`}
else if(id==="installatie_videofoon"){title=`${q} - ${onderdeel} ${waarneming.toLowerCase()} - Videofoon - ${loc}`}
else if(id==="installatie_loze_leiding"){title=`${q} - ${onderdeel} ${waarneming.toLowerCase()} - ${loc}`}
else if(id==="installatie_designradiator"){
if(onderdeel==="Radiator")title=`${q} - Designradiator ${waarneming.toLowerCase()} - Badkamer`;
else title=`${q} - ${onderdeel} ${waarneming.toLowerCase()} - Designradiator - Badkamer`}
else{title=`${q} - ${onderdeel} ${waarneming.toLowerCase()} - ${systeem} - ${loc}`}
if(id==="installatie_warmtepomp"&&(onderdeel==="Manometer broncircuit"||onderdeel==="Manometer verwarmingsinstallatie"))desc=`De ${onderdeel.toLowerCase()} van de warmtepomp geeft ${waarneming.toLowerCase()} aan.`;
else if(id==="installatie_wtw"&&onderdeel==="WTW-unit"&&waarneming==="Werkt niet")desc=`De WTW-unit in de technische ruimte functioneert niet.`;
else if(id==="installatie_omvormer"&&onderdeel==="Omvormer"&&waarneming==="Storing zichtbaar")desc=`Op de omvormer voor de zonnepanelen is een storing zichtbaar.`;
else if(id==="installatie_vloerverdeler"&&onderdeel==="Verdeler"&&waarneming==="Lekt")desc=`Lekkage vastgesteld aan de vloerverdeler in ${loc.toLowerCase()}.`;
else if(id==="installatie_elektra"&&onderdeel==="Groepenverklaring"&&waarneming==="Ontbreekt")desc=`De groepenverklaring in de meterkast ontbreekt.`;
else if(id==="installatie_elektra"&&onderdeel==="Groepenverklaring"&&waarneming==="Komt niet overeen met de groepenkast")desc=`De groepenverklaring in de meterkast komt niet overeen met de werkelijke indeling van de groepenkast.`;
else if(id==="installatie_rookmelder"&&onderdeel==="Stofkap"&&waarneming==="Stofkap ontbreekt")desc=`De stofkap van de rookmelder ontbreekt in de vluchtroute.`;
else if(id==="installatie_designradiator"&&onderdeel==="Radiator"&&waarneming==="Beschadigd")desc=`De designradiator in de badkamer is beschadigd.`;
else if(id==="installatie_designradiator"&&onderdeel==="Radiator"&&waarneming==="Los aangebracht")desc=`De designradiator in de badkamer zit los.`;
else if(id==="installatie_designradiator"&&onderdeel==="Radiator"&&waarneming==="Scheef aangebracht")desc=`De designradiator in de badkamer is scheef aangebracht.`;
else if(id==="installatie_designradiator"&&onderdeel==="Radiator"&&waarneming==="Werkt niet")desc=`De designradiator in de badkamer functioneert niet.`;
else if(id==="installatie_designradiator"&&onderdeel==="Radiator"&&waarneming==="Lekt")desc=`Lekkage vastgesteld bij de designradiator in de badkamer.`;
else if(id==="installatie_designradiator"&&onderdeel==="Bevestiging"&&waarneming==="Los aangebracht")desc=`De bevestiging van de designradiator in de badkamer zit los.`;
else if(id==="installatie_designradiator"&&onderdeel==="Bevestiging"&&waarneming==="Beschadigd")desc=`De bevestiging van de designradiator in de badkamer is beschadigd.`;
else if(id==="installatie_designradiator"&&onderdeel==="Bediening"&&waarneming==="Werkt niet")desc=`De bediening van de designradiator in de badkamer functioneert niet.`;
else if(id==="installatie_designradiator"&&onderdeel==="Bediening"&&waarneming==="Beschadigd")desc=`De bediening van de designradiator in de badkamer is beschadigd.`;
else if(id==="installatie_designradiator"&&onderdeel==="Afstandsbediening"&&waarneming==="Ontbreekt")desc=`De afstandsbediening van de designradiator ontbreekt.`;
else if(id==="installatie_designradiator"&&onderdeel==="Afstandsbediening"&&waarneming==="Beschadigd")desc=`De afstandsbediening van de designradiator is beschadigd.`;
else if(id==="installatie_designradiator"&&onderdeel==="Afstandsbediening"&&waarneming==="Werkt niet")desc=`De afstandsbediening van de designradiator functioneert niet.`;
else if(id==="installatie_videofoon"&&waarneming==="Beeld ontbreekt")desc=`De videofoon in ${loc.toLowerCase()} geeft geen beeld.`;
else if(id==="installatie_videofoon"&&waarneming==="Geluid ontbreekt")desc=`De videofoon in ${loc.toLowerCase()} geeft geen geluid.`;
else if(id==="installatie_videofoon"&&waarneming==="Deuropener werkt niet")desc=`De deuropener van de videofoon in ${loc.toLowerCase()} functioneert niet.`;
else if(id==="installatie_loze_leiding"){desc=`${onderdeel} in ${loc.toLowerCase()} is ${waarneming.toLowerCase()}.`;if(v("controlWire")==="Nee")desc+=` De loze leiding is niet voorzien van een controledraad.`;if(v("controlWire")==="Ja")desc+=` De loze leiding is voorzien van een controledraad.`;}
else if(id==="installatie_wasmachine"&&waarneming==="Lekt")desc=`Lekkage vastgesteld bij ${onderdeel.toLowerCase()} van de wasmachine-/drogeropstelling in ${loc.toLowerCase()}.`;
else if(id==="installatie_ventilatie"&&waarneming==="Sluit niet aan"&&v("instSurface")!=="Niet van toepassing")desc=`Het ${onderdeel.toLowerCase()} van de ventilatie in ${loc.toLowerCase()} sluit niet aan op het ${v("instSurface").toLowerCase()}.`;
else if(waarneming==="Ontbreekt")desc=`${onderdeel} van de ${systeem.toLowerCase()} ontbreekt${loc?` in ${loc.toLowerCase()}`:""}.`;
else if(waarneming==="Niet aangesloten")desc=`${onderdeel} van de ${systeem.toLowerCase()} is${loc?` in ${loc.toLowerCase()}`:""} niet aangesloten.`;
else if(waarneming==="Lekt"||waarneming==="Lekkage zichtbaar")desc=`Lekkage vastgesteld bij ${onderdeel.toLowerCase()} van de ${systeem.toLowerCase()}${loc?` in ${loc.toLowerCase()}`:""}.`;
else desc=`${onderdeel} van de ${systeem.toLowerCase()} is${loc?` in ${loc.toLowerCase()}`:""} ${waarneming.toLowerCase()}.`;
let warning="";
if(id==="installatie_warmtepomp")warning="Let op: controleer welke manometer wordt afgelezen. De manometer van het broncircuit hoort bij een afzonderlijk gesloten circuit met een ander medium en mag niet als de waterinstallatie van de woning worden bijgevuld.";
k=["Installaties en installatieonderdelen dienen compleet, deugdelijk gemonteerd en passend aangesloten te zijn overeenkomstig de projectspecificatie en de verwerkingsvoorschriften van de fabrikant.","Projectspecifieke technische omschrijving, installatietekeningen, productdocumentatie en verwerkingsvoorschriften van de fabrikant.",`De waarneming ‘${waarneming.toLowerCase()}’ betreft een zichtbare afwijking, ontbrekend onderdeel of functieverlies van de installatie.`,"Beschrijf uitsluitend wat zichtbaar of functioneel is vastgesteld. Doe geen uitspraak over de oorzaak of herstelwijze.",warning||"Controleer locatie, onderdeel, aansluiting en zichtbare werking."];}
if(id.startsWith("sanitair_")){q="Opleverpunt";let room=v("sanRoom"),part=v("sanPart"),issue=v("sanIssue");title=`${q} - ${issue} - ${part} - ${room}`;if(issue==="Ontbreekt")desc=`${part} ontbreekt in ${room.toLowerCase()}.`;else if(issue==="Beschadigd")desc=`Beschadiging aan ${part.toLowerCase()} in ${room.toLowerCase()}.`;else if(issue==="Kras")desc=`Kras aan ${part.toLowerCase()} in ${room.toLowerCase()}.`;else if(issue==="Los")desc=`${part} zit los in ${room.toLowerCase()}.`;else if(issue==="Scheef gemonteerd")desc=`${part} is scheef gemonteerd in ${room.toLowerCase()}.`;else if(issue==="Niet compleet")desc=`${part} is niet compleet in ${room.toLowerCase()}.`;else if(issue==="Lekt")desc=`Lekkage vastgesteld bij ${part.toLowerCase()} in ${room.toLowerCase()}.`;else if(issue==="Druppelt")desc=`De ${part.toLowerCase()} in ${room.toLowerCase()} druppelt.`;else if(issue==="Werkt niet")desc=`${part} in ${room.toLowerCase()} functioneert niet.`;else if(issue==="Spoelt niet goed")desc=`De toiletpot in ${room.toLowerCase()} spoelt niet goed door.`;else if(issue==="Afvoer onvoldoende")desc=`De afvoer van ${part.toLowerCase()} in ${room.toLowerCase()} functioneert onvoldoende.`;else if(id==="sanitair_toilet"&&part==="Kitwerk"&&issue==="Kit ontbreekt")desc=`De kitvoeg ter plaatse van de toiletpot in ${room.toLowerCase()} ontbreekt.`;
else if(id==="sanitair_toilet"&&part==="Kitwerk"&&issue==="Kit onthecht")desc=`De kitvoeg ter plaatse van de toiletpot in ${room.toLowerCase()} is onthecht.`;
else if(id==="sanitair_toilet"&&part==="Kitwerk"&&issue==="Onvoldoende afgewerkt")desc=`De kitvoeg ter plaatse van de toiletpot in ${room.toLowerCase()} is onvoldoende afgewerkt.`;
else if(issue==="Kit ontbreekt")desc=`Kitwerk ontbreekt bij ${part.toLowerCase()} in ${room.toLowerCase()}.`;
else if(issue==="Kit onthecht")desc=`Het kitwerk bij ${part.toLowerCase()} in ${room.toLowerCase()} is onthecht.`;
else if(issue==="Onvoldoende afgewerkt")desc=`${part} is onvoldoende afgewerkt in ${room.toLowerCase()}.`;
else if(["Lade links","Lade rechts"].includes(part)&&issue==="Loopt zwaar")desc=`De ${part.toLowerCase()} van het badmeubel in ${room.toLowerCase()} loopt zwaar.`;
else if(["Lade links","Lade rechts"].includes(part)&&issue==="Sluit niet")desc=`De ${part.toLowerCase()} van het badmeubel in ${room.toLowerCase()} sluit niet goed.`;
else if(["Lade links","Lade rechts"].includes(part)&&issue==="Scheef gemonteerd")desc=`De ${part.toLowerCase()} van het badmeubel in ${room.toLowerCase()} is scheef gemonteerd.`;
else if(["Lade links","Lade rechts"].includes(part)&&issue==="Los gemonteerd")desc=`De ${part.toLowerCase()} van het badmeubel in ${room.toLowerCase()} zit los.`;
else if(part==="Badmeubel"&&issue==="Beschadigd")desc=`Het badmeubel in ${room.toLowerCase()} is beschadigd.`;
else if(part==="Badmeubel"&&issue==="Kras")desc=`Kras aan het badmeubel in ${room.toLowerCase()}.`;
else desc=`${issue} bij ${part.toLowerCase()} in ${room.toLowerCase()}.`;if(id==="sanitair_toilet"&&part==="Toiletpot"){desc+=` De gemeten hoogte van de toiletpot, gemeten zonder toiletbril, bedraagt ${n("toiletHeight")} cm.`;let mw=v("toiletMorework");if(mw&&mw!=="Niet van toepassing")desc+=` De toiletpot is ${mw.toLowerCase()}.`;}k=["Sanitair en bijbehorende onderdelen dienen compleet, deugdelijk gemonteerd, bruikbaar en vrij van zichtbare lekkage te zijn.","Projectspecifieke technische omschrijving, productdocumentatie, montagevoorschriften en gebruikelijke uitvoeringspraktijk.","De gekozen waarneming betreft een zichtbare afwijking, ontbrekend onderdeel, functieverlies of lekkage en wordt daarom als opleverpunt vastgelegd.","Controleer sanitair visueel en functioneel. Leg alleen vast wat daadwerkelijk is gecontroleerd.","Controleer bevestiging, werking, waterloop, afvoer, aansluitingen en kitwerk. Bij toilethoogte geldt doorgaans gebruikelijke praktijk en niet automatisch een expliciete BBL-eis."];}
return{q,title,desc,k};}
const exteriorLocations=["Balkon","Galerij","Gevel","Buitenruimte voor","Buitenruimte achter"];
function selectedLocation(){if(current?.id==="kitwerk")return v("kitPlace");if(current?.cardType==="expert")return v("eLoc");return v("location")}
function isExterior(){let loc=selectedLocation();return exteriorLocations.includes(loc)||["Kozijn buiten","Gevel","Balkon","Galerij"].includes(loc)}
function applyVve(result){if(v("projectType")==="Appartement"&&isExterior()){result.q="Constatering t.b.v. VvE";result.title=result.title.replace(/^(Opleverpunt|Constatering)/,"Constatering t.b.v. VvE");result.desc+=" De buitenschil behoort tot de gemeenschappelijke ruimten van de VvE en valt daarmee buiten de scope van deze individuele oplevering. De constatering is uitsluitend opgenomen zodat de aannemer en de VvE hiervan kennis kunnen nemen en de eventuele herstelverantwoordelijkheid kunnen beoordelen."}return result}
function registrationResult(){let o=D.objects.find(x=>x.id===$("object").value),obs=current.name,loc=v("location"),part=v("part"),type=v("type"),micro=v("microLocation"),desc;if(current.id==="manco")desc=`${part} ontbreekt aan de ${type.toLowerCase()} in ${loc.toLowerCase()}.`;else if(current.id==="niet_compleet")desc=`${part} van de ${type.toLowerCase()} in ${loc.toLowerCase()} is niet compleet.`;else if(current.id==="niet_afgemonteerd"){let article=(type==="Spackwerk"||type==="Spuitwerk")?"het":"de";desc=`${part} van ${article} ${type.toLowerCase()} in ${loc.toLowerCase()} is niet afgemonteerd.`;}else if(current.id==="sluit_niet_aan")desc=part==="Ventiel"?`Ventiel sluit niet aan op het plafond in ${loc.toLowerCase()}.`:`${part} sluit niet aan in ${loc.toLowerCase()}.`;else if(current.id==="lakbeschadiging"&&micro&&micro!=="Niet gespecificeerd")desc=`Lakbeschadiging aan de ${micro.toLowerCase()} van ${part.toLowerCase()} van de ${type.toLowerCase()} in ${loc.toLowerCase()}.`;else if(type==="Waterslag"||part==="Waterslag")desc=`${obs} aan de waterslag in ${loc.toLowerCase()}.`;else {let article=(type==="Spackwerk"||type==="Spuitwerk")?"het":"de";desc=`${obs} waargenomen aan ${part.toLowerCase()} van ${article} ${type.toLowerCase()} in ${loc.toLowerCase()}.`;}return{q:"Opleverpunt",title:`Opleverpunt - ${obs} - ${o.name} - ${loc}`,desc,k:[]}}
function render(){if(!current)return;let r=current.cardType==="expert"?expertResult():registrationResult();r=applyVve(r);let e=v("extra").trim(),pa=v("projectAgreement").trim();$("titleOut").textContent=r.title;$("descOut").textContent=r.desc+(pa?`\nProjectspecifieke afspraak / meerwerk: ${pa}`:"")+(e?`\nAanvullende toelichting inspecteur: ${e}`:"");$("adviceOut").textContent=`KOMPAS-advies: ${r.q}.`;if(current.cardType==="expert"){$("assessment").className=`note ${r.q==="Opleverpunt"?"bad":"ok"}`;$("assessment").textContent=`KOMPAS-inschatting: ${r.q}.`;r.k.forEach((x,i)=>$("know"+i).textContent=x)}let warn=current.id==="lakbeschadiging"&&["Scharnier","Deurbeslag","Slot","Cilinder","Rubber","Beglazing"].includes(v("part"))?"Gebruik hier waarschijnlijk ‘Beschadiging’ in plaats van ‘Lakbeschadiging’.":"";$("warning").classList.toggle("hidden",!warn);$("warning").textContent=warn}
async function copy(id){try{await navigator.clipboard.writeText($(id).textContent);alert("Gekopieerd.")}catch{alert("Kopiëren lukte niet.")}}
function logEntry(){let note=prompt("Wat klopt niet of wat ontbreekt?");if(!note)return;let text=$("logText").value+`\n---\nDatum: ${new Date().toLocaleString("nl-NL")}\nKaart: ${current.name}\nTitel: ${$("titleOut").textContent}\nOpmerking: ${note}\n`;$("logText").value=text;localStorage.setItem("kompas-logbook",text);alert("Toegevoegd aan het KOMPAS-logboek.")}
$("version").textContent=D.meta.version;$("subtitle").textContent=D.meta.subtitle;$("projectType").value=localStorage.getItem("kompas-projecttype")||"Grondgebonden";$("projectType").onchange=()=>{localStorage.setItem("kompas-projecttype",v("projectType"));render();renderList()};$("search").oninput=renderList;$("object").onchange=objectChanged;$("type").onchange=typeChanged;$("part").onchange=render;$("location").onchange=render;$("microLocation").onchange=render;$("projectAgreement").oninput=render;$("extra").oninput=render;document.querySelectorAll("[data-copy]").forEach(b=>b.onclick=()=>copy(b.dataset.copy));$("quickLog").onclick=logEntry;$("logText").value=localStorage.getItem("kompas-logbook")||"";$("logText").oninput=()=>localStorage.setItem("kompas-logbook",$("logText").value);$("downloadLog").onclick=()=>{let a=document.createElement("a"),blob=new Blob([$ ("logText").value],{type:"text/plain"});a.href=URL.createObjectURL(blob);a.download="KOMPAS_logboek.txt";a.click()};renderList();